version: '3.4'

services:
  empire-service:
    image: empire-service:latest
    build:
      context: .
      dockerfile: Empire.Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "3001:80"
    healthcheck:
      # disable: true
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 40s

  alliance-service:
    image: alliance-service:latest
    build:
      context: .
      dockerfile: Alliance.Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "3002:80"

  hansolo-service:
    image: hansolo-service:latest
    build:
      context: .
      dockerfile: HanSolo.Service/Dockerfile
